services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    user: node
    container_name: projeto1_api
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/home/node/app
    env_file:
      - .env

  db:
    image: mysql:8.0
    container_name: projeto1_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env

volumes:
  mysql_data:
